### PR TITLE
Update sonataflow CRDs to include SonataflowClusterPlatform

### PR DESCRIPTION
**Pull request by masayag**

### CODE REVIEW

**Review by gabriel-farache — APPROVED** [review]

**Comment by rgolangh** [comment]
diff is too large. you sure this is just including platform?

**Comment by masayag** [comment]
It contains all of the CRDs changes generated by the latest code base version.

**Comment by masayag** [comment]
I simply copied the file from https://github.com/parodos-dev/orchestrator-helm-chart/blob/main/charts/orchestrator/crds/sonataflow-operator.yaml to this repository.

**Comment by rgolangh** [comment]
for the upstream operator I source all crds from the apache/incubator 

```
curl -s https://raw.githubusercontent.com/apache/incubator-kie-kogito-serverless-operator/main/operator.yaml | yq  'select(.kind == "CustomResourceDefinition")' > sonataflow-crds.yaml
```

**Comment by masayag** [comment]
> for the upstream operator I source all crds from the apache/incubator
> 
> ```
> curl -s https://raw.githubusercontent.com/apache/incubator-kie-kogito-serverless-operator/main/operator.yaml | yq  'select(.kind == "CustomResourceDefinition")' > sonataflow-crds.yaml
> ```

I updated the PR with the result of that command.

**Comment by rgolangh** [comment]
I'll take a closer look to see my yq expression is okay

**Pull request merged**
